name: Execute Linters and Tests
on: pull_request 

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install Dependencies
        run: npm install

      - name: Run Linters
        run: npm run lint

      - name: Run tests
        run: xvfb-run -a npm run test
