on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm install

      - name: Run Linters
        run: npm run lint

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
